#!/bin/sh
set -eu

MYSQL_HOST="${MYSQL_HOST:-source-db}"
MYSQL_PORT="${MYSQL_PORT:-3306}"
MYSQL_DATABASE="${MYSQL_DATABASE:-sdp_pusat}"
MYSQL_USER="${MYSQL_USER:-root}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-rootpass}"
SEED_ROWS="${SEED_ROWS:-10000}"
FORCE_RESEED="${FORCE_RESEED:-false}"

echo "Waiting for MariaDB at ${MYSQL_HOST}:${MYSQL_PORT}..."
until mariadb-admin --protocol=tcp -h "${MYSQL_HOST}" -P "${MYSQL_PORT}" \
  -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" ping --silent >/dev/null 2>&1
do
  sleep 2
done

mysql_exec() {
  mariadb --protocol=tcp \
    -h "${MYSQL_HOST}" -P "${MYSQL_PORT}" \
    -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" \
    "${MYSQL_DATABASE}" "$@"
}

mysql_exec_server() {
  mariadb --protocol=tcp \
    -h "${MYSQL_HOST}" -P "${MYSQL_PORT}" \
    -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "$@"
}

echo "Ensuring database ${MYSQL_DATABASE} and readonly grants..."
mysql_exec_server <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
CREATE USER IF NOT EXISTS 'readonly_source_user'@'%' IDENTIFIED BY 'source_pass';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.* TO 'readonly_source_user'@'%';
FLUSH PRIVILEGES;
SQL

if [ "${FORCE_RESEED}" = "true" ]; then
  echo "FORCE_RESEED=true, dropping old source tables..."
  mysql_exec <<'SQL'
DROP TABLE IF EXISTS cif_mapping;
DROP TABLE IF EXISTS perkara;
DROP TABLE IF EXISTS identitas;
SQL
fi

echo "Ensuring production-like source tables exist..."
mysql_exec <<'SQL'
CREATE TABLE IF NOT EXISTS identitas (
  NOMOR_INDUK VARCHAR(15) NOT NULL,
  ID_JENIS_SUKU VARCHAR(20) DEFAULT '',
  ID_JENIS_SUKU_LAIN VARCHAR(255) DEFAULT '',
  ID_JENIS_RAMBUT VARCHAR(20) DEFAULT '',
  ID_JENIS_MUKA VARCHAR(20) DEFAULT '',
  ID_JENIS_PENDIDIKAN VARCHAR(20) DEFAULT '',
  ID_JENIS_PENDIDIKAN_LAIN VARCHAR(255) DEFAULT '',
  ID_JENIS_TANGAN VARCHAR(20) DEFAULT '',
  ID_JENIS_AGAMA VARCHAR(20) DEFAULT '',
  ID_JENIS_AGAMA_LAIN VARCHAR(255) DEFAULT '',
  ID_JENIS_PEKERJAAN VARCHAR(20) DEFAULT '',
  ID_JENIS_PEKERJAAN_LAIN VARCHAR(255) DEFAULT '',
  ID_USER VARCHAR(50) DEFAULT '',
  ID_BENTUK_MATA VARCHAR(20) DEFAULT '',
  ID_WARNA_MATA VARCHAR(20) DEFAULT '',
  ID_JENIS_KEAHLIAN_1 VARCHAR(20) DEFAULT '',
  ID_JENIS_KEAHLIAN_1_LAIN VARCHAR(255) DEFAULT '',
  ID_JENIS_KEAHLIAN_2 VARCHAR(20) DEFAULT '',
  ID_JENIS_KEAHLIAN_2_LAIN VARCHAR(255) DEFAULT '',
  ID_JENIS_HIDUNG VARCHAR(20) DEFAULT '',
  ID_JENIS_LEVEL_1 VARCHAR(20) DEFAULT '',
  ID_JENIS_MULUT VARCHAR(20) DEFAULT '',
  ID_JENIS_LEVEL_2 VARCHAR(20) DEFAULT '',
  ID_JENIS_WARGANEGARA VARCHAR(20) DEFAULT '',
  ID_NEGARA_ASING VARCHAR(20) DEFAULT '',
  ID_PROPINSI VARCHAR(20) DEFAULT '',
  ID_PROPINSI_LAIN VARCHAR(255) DEFAULT '',
  ID_JENIS_STATUS_PERKAWINAN VARCHAR(20) DEFAULT '',
  ID_JENIS_KELAMIN VARCHAR(10) DEFAULT '',
  ID_JENIS_KAKI VARCHAR(20) DEFAULT '',
  ID_TEMPAT_LAHIR VARCHAR(20) DEFAULT '',
  ID_TEMPAT_LAHIR_LAIN VARCHAR(255) DEFAULT '',
  ID_KOTA VARCHAR(20) DEFAULT '',
  ID_KOTA_LAIN VARCHAR(255) DEFAULT '',
  ID_TEMPAT_ASAL VARCHAR(20) DEFAULT '',
  ID_TEMPAT_ASAL_LAIN VARCHAR(255) DEFAULT '',
  RESIDIVIS VARCHAR(20) DEFAULT '',
  RESIDIVIS_COUNTER INT DEFAULT 0,
  NAMA_LENGKAP VARCHAR(255) DEFAULT '',
  NIK VARCHAR(32) DEFAULT '',
  NAMA_ALIAS1 VARCHAR(255) DEFAULT '',
  NAMA_ALIAS2 VARCHAR(255) DEFAULT '',
  NAMA_ALIAS3 VARCHAR(255) DEFAULT '',
  NAMA_KECIL1 VARCHAR(255) DEFAULT '',
  NAMA_KECIL2 VARCHAR(255) DEFAULT '',
  NAMA_KECIL3 VARCHAR(255) DEFAULT '',
  TANGGAL_LAHIR DATE NULL,
  IS_WBP_BERESIKO_TINGGI TINYINT(1) DEFAULT 0,
  IS_PENGARUH_TERHADAP_MASYARAKAT TINYINT(1) DEFAULT 0,
  IS_BACA_LATIN TINYINT(1) DEFAULT 0,
  IS_BACA_QURAN TINYINT(1) DEFAULT 0,
  IS_DISABILITAS TINYINT(1) DEFAULT 0,
  ALAMAT VARCHAR(255) DEFAULT '',
  ALAMAT_ALTERNATIF VARCHAR(255) DEFAULT '',
  KODEPOS VARCHAR(10) DEFAULT '',
  TELEPON VARCHAR(32) DEFAULT '',
  ALAMAT_PEKERJAAN VARCHAR(255) DEFAULT '',
  KETERANGAN_PEKERJAAN VARCHAR(255) DEFAULT '',
  MINAT VARCHAR(255) DEFAULT '',
  NM_AYAH VARCHAR(255) DEFAULT '',
  TMP_TGL_AYAH VARCHAR(255) DEFAULT '',
  NM_IBU VARCHAR(255) DEFAULT '',
  TMP_TGL_IBU VARCHAR(255) DEFAULT '',
  NM_SAUDARA VARCHAR(255) DEFAULT '',
  ANAKKE INT DEFAULT 0,
  JML_SAUDARA INT DEFAULT 0,
  JML_ISTRI_SUAMI INT DEFAULT 0,
  NM_ISTRI_SUAMI VARCHAR(255) DEFAULT '',
  TMP_TGL_ISTRI_SUAMI VARCHAR(255) DEFAULT '',
  JML_ANAK INT DEFAULT 0,
  NM_ANAK VARCHAR(255) DEFAULT '',
  TELEPHONE_KELUARGA VARCHAR(32) DEFAULT '',
  TINGGI INT DEFAULT 0,
  BERAT INT DEFAULT 0,
  CACAT VARCHAR(255) DEFAULT '',
  CIRI VARCHAR(255) DEFAULT '',
  CIRI2 VARCHAR(255) DEFAULT '',
  CIRI3 VARCHAR(255) DEFAULT '',
  FOTO_DEPAN VARCHAR(255) DEFAULT '',
  FOTO_KANAN VARCHAR(255) DEFAULT '',
  FOTO_KIRI VARCHAR(255) DEFAULT '',
  FOTO_CLOSEUP VARCHAR(255) DEFAULT '',
  FOTO_CIRI_1 VARCHAR(255) DEFAULT '',
  FOTO_CIRI_2 VARCHAR(255) DEFAULT '',
  FOTO_CIRI_3 VARCHAR(255) DEFAULT '',
  KONSOLIDASI TINYINT(1) DEFAULT 0,
  KONSOLIDASI_IMAGE TINYINT(1) DEFAULT 0,
  ID_KACAMATA VARCHAR(20) DEFAULT '',
  ID_TELINGA VARCHAR(20) DEFAULT '',
  ID_WARNAKULIT VARCHAR(20) DEFAULT '',
  ID_BENTUKRAMBUT VARCHAR(20) DEFAULT '',
  ID_BENTUKBIBIR VARCHAR(20) DEFAULT '',
  ID_LENGAN VARCHAR(20) DEFAULT '',
  NOMOR_INDUK_NASIONAL VARCHAR(32) DEFAULT '',
  IS_VERIFIKASI TINYINT(1) DEFAULT 0,
  IS_DELETED TINYINT(1) DEFAULT 0,
  CREATED DATETIME NULL,
  CREATED_BY VARCHAR(50) DEFAULT '',
  UPDATED DATETIME NULL,
  UPDATED_BY VARCHAR(50) DEFAULT '',
  UPDATED_AT DATETIME NULL,
  PRIMARY KEY (NOMOR_INDUK),
  KEY idx_identitas_updated_at (UPDATED_AT),
  KEY idx_identitas_updated (UPDATED),
  KEY idx_identitas_nik (NIK),
  KEY idx_identitas_nomor_induk_nasional (NOMOR_INDUK_NASIONAL),
  KEY idx_identitas_tanggal_lahir (TANGGAL_LAHIR),
  KEY idx_identitas_nama_lengkap (NAMA_LENGKAP(100))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS perkara (
  ID_PERKARA BIGINT NOT NULL AUTO_INCREMENT,
  NOMOR_INDUK VARCHAR(15) NOT NULL,
  ID_UPT VARCHAR(3) DEFAULT NULL,
  STATUS_PERKARA VARCHAR(50) DEFAULT '',
  UPDATED_AT DATETIME NULL,
  PRIMARY KEY (ID_PERKARA),
  KEY idx_perkara_nomor_induk (NOMOR_INDUK),
  KEY idx_perkara_id_upt (ID_UPT)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cif_mapping (
  NOMOR_INDUK VARCHAR(15) NOT NULL,
  CIF_NUMBER VARCHAR(32) NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (NOMOR_INDUK),
  UNIQUE KEY uq_cif_mapping_cif_number (CIF_NUMBER)
) ENGINE=InnoDB;
SQL

existing_rows="$(mysql_exec -Nse "SELECT COUNT(*) FROM identitas;")"
if [ "${existing_rows}" -gt 0 ] && [ "${FORCE_RESEED}" != "true" ]; then
  echo "Table identitas already has ${existing_rows} rows. Skip seeding (set FORCE_RESEED=true to rebuild)."
  exit 0
fi

if [ "${FORCE_RESEED}" = "true" ]; then
  echo "FORCE_RESEED=true, truncating tables..."
  mysql_exec <<'SQL'
TRUNCATE TABLE cif_mapping;
TRUNCATE TABLE perkara;
TRUNCATE TABLE identitas;
SQL
fi

echo "Seeding ${SEED_ROWS} synthetic rows into identitas..."
mysql_exec <<SQL
SET @seed_rows := ${SEED_ROWS};

INSERT INTO identitas (
  NOMOR_INDUK,
  ID_JENIS_SUKU,
  ID_JENIS_SUKU_LAIN,
  ID_JENIS_RAMBUT,
  ID_JENIS_MUKA,
  ID_JENIS_PENDIDIKAN,
  ID_JENIS_PENDIDIKAN_LAIN,
  ID_JENIS_TANGAN,
  ID_JENIS_AGAMA,
  ID_JENIS_AGAMA_LAIN,
  ID_JENIS_PEKERJAAN,
  ID_JENIS_PEKERJAAN_LAIN,
  ID_USER,
  ID_BENTUK_MATA,
  ID_WARNA_MATA,
  ID_JENIS_KEAHLIAN_1,
  ID_JENIS_KEAHLIAN_1_LAIN,
  ID_JENIS_KEAHLIAN_2,
  ID_JENIS_KEAHLIAN_2_LAIN,
  ID_JENIS_HIDUNG,
  ID_JENIS_LEVEL_1,
  ID_JENIS_MULUT,
  ID_JENIS_LEVEL_2,
  ID_JENIS_WARGANEGARA,
  ID_NEGARA_ASING,
  ID_PROPINSI,
  ID_PROPINSI_LAIN,
  ID_JENIS_STATUS_PERKAWINAN,
  ID_JENIS_KELAMIN,
  ID_JENIS_KAKI,
  ID_TEMPAT_LAHIR,
  ID_TEMPAT_LAHIR_LAIN,
  ID_KOTA,
  ID_KOTA_LAIN,
  ID_TEMPAT_ASAL,
  ID_TEMPAT_ASAL_LAIN,
  RESIDIVIS,
  RESIDIVIS_COUNTER,
  NAMA_LENGKAP,
  NIK,
  NAMA_ALIAS1,
  NAMA_ALIAS2,
  NAMA_ALIAS3,
  NAMA_KECIL1,
  NAMA_KECIL2,
  NAMA_KECIL3,
  TANGGAL_LAHIR,
  IS_WBP_BERESIKO_TINGGI,
  IS_PENGARUH_TERHADAP_MASYARAKAT,
  IS_BACA_LATIN,
  IS_BACA_QURAN,
  IS_DISABILITAS,
  ALAMAT,
  ALAMAT_ALTERNATIF,
  KODEPOS,
  TELEPON,
  ALAMAT_PEKERJAAN,
  KETERANGAN_PEKERJAAN,
  MINAT,
  NM_AYAH,
  TMP_TGL_AYAH,
  NM_IBU,
  TMP_TGL_IBU,
  NM_SAUDARA,
  ANAKKE,
  JML_SAUDARA,
  JML_ISTRI_SUAMI,
  NM_ISTRI_SUAMI,
  TMP_TGL_ISTRI_SUAMI,
  JML_ANAK,
  NM_ANAK,
  TELEPHONE_KELUARGA,
  TINGGI,
  BERAT,
  CACAT,
  CIRI,
  CIRI2,
  CIRI3,
  FOTO_DEPAN,
  FOTO_KANAN,
  FOTO_KIRI,
  FOTO_CLOSEUP,
  FOTO_CIRI_1,
  FOTO_CIRI_2,
  FOTO_CIRI_3,
  KONSOLIDASI,
  KONSOLIDASI_IMAGE,
  ID_KACAMATA,
  ID_TELINGA,
  ID_WARNAKULIT,
  ID_BENTUKRAMBUT,
  ID_BENTUKBIBIR,
  ID_LENGAN,
  NOMOR_INDUK_NASIONAL,
  IS_VERIFIKASI,
  IS_DELETED,
  CREATED,
  CREATED_BY,
  UPDATED,
  UPDATED_BY,
  UPDATED_AT
)
SELECT
  CONCAT(
    LPAD(src.id_upt_num, 3, '0'),
    src.year_num,
    LPAD(src.month_num, 2, '0'),
    LPAD(src.day_num, 2, '0'),
    LPAD(src.seq_num, 4, '0')
  ) AS NOMOR_INDUK,
  CONCAT('SUK', MOD(src.person_key, 40)) AS ID_JENIS_SUKU,
  '' AS ID_JENIS_SUKU_LAIN,
  CONCAT('RMB', MOD(src.person_key, 5)) AS ID_JENIS_RAMBUT,
  CONCAT('MUK', MOD(src.person_key, 5)) AS ID_JENIS_MUKA,
  CONCAT('PND', MOD(src.person_key, 10)) AS ID_JENIS_PENDIDIKAN,
  '' AS ID_JENIS_PENDIDIKAN_LAIN,
  CONCAT('TGN', MOD(src.person_key, 4)) AS ID_JENIS_TANGAN,
  CONCAT('AGM', MOD(src.person_key, 8)) AS ID_JENIS_AGAMA,
  '' AS ID_JENIS_AGAMA_LAIN,
  CONCAT('PKJ', MOD(src.person_key, 25)) AS ID_JENIS_PEKERJAAN,
  '' AS ID_JENIS_PEKERJAAN_LAIN,
  CONCAT('USR', MOD(src.n, 500)) AS ID_USER,
  CONCAT('MAT', MOD(src.person_key, 5)) AS ID_BENTUK_MATA,
  CONCAT('WAR', MOD(src.person_key, 5)) AS ID_WARNA_MATA,
  CONCAT('AHL', MOD(src.person_key, 20)) AS ID_JENIS_KEAHLIAN_1,
  '' AS ID_JENIS_KEAHLIAN_1_LAIN,
  CONCAT('AHL', MOD(src.person_key + 7, 20)) AS ID_JENIS_KEAHLIAN_2,
  '' AS ID_JENIS_KEAHLIAN_2_LAIN,
  CONCAT('HDG', MOD(src.person_key, 5)) AS ID_JENIS_HIDUNG,
  CONCAT('LV1', MOD(src.person_key, 12)) AS ID_JENIS_LEVEL_1,
  CONCAT('MLT', MOD(src.person_key, 5)) AS ID_JENIS_MULUT,
  CONCAT('LV2', MOD(src.person_key, 12)) AS ID_JENIS_LEVEL_2,
  IF(MOD(src.person_key, 50) = 0, '2', '1') AS ID_JENIS_WARGANEGARA,
  IF(MOD(src.person_key, 50) = 0, CONCAT('NEG', MOD(src.person_key, 15)), '') AS ID_NEGARA_ASING,
  CONCAT('PRP', MOD(src.person_key, 38)) AS ID_PROPINSI,
  '' AS ID_PROPINSI_LAIN,
  CONCAT('KWN', MOD(src.person_key, 5)) AS ID_JENIS_STATUS_PERKAWINAN,
  IF(MOD(src.person_key, 2) = 0, '1', '2') AS ID_JENIS_KELAMIN,
  CONCAT('KAK', MOD(src.person_key, 4)) AS ID_JENIS_KAKI,
  CONCAT('TPL', LPAD(1 + MOD(src.person_key, 300), 4, '0')) AS ID_TEMPAT_LAHIR,
  '' AS ID_TEMPAT_LAHIR_LAIN,
  CONCAT('KOT', LPAD(1 + MOD(src.person_key, 200), 4, '0')) AS ID_KOTA,
  '' AS ID_KOTA_LAIN,
  CONCAT('ASL', LPAD(1 + MOD(src.person_key, 200), 4, '0')) AS ID_TEMPAT_ASAL,
  '' AS ID_TEMPAT_ASAL_LAIN,
  IF(MOD(src.person_key, 9) = 0, 'YA', 'TIDAK') AS RESIDIVIS,
  MOD(src.person_key, 4) AS RESIDIVIS_COUNTER,
  CASE
    WHEN MOD(src.n, 83) = 0 THEN ''
    WHEN MOD(src.n, 97) = 0 THEN CONCAT('NAMA WBP ', LPAD(src.n, 5, '0'))
    ELSE CONCAT(
      ELT(1 + MOD(src.person_key, 20), 'BUDI', 'AHMAD', 'JOKO', 'RIZKY', 'FAJAR', 'BAGUS', 'RAMA', 'YUSUF', 'DANI', 'AGUS', 'ARI', 'HENDRA', 'RUDI', 'YOGA', 'SANDI', 'IRFAN', 'RIZAL', 'ILHAM', 'NUGROHO', 'BAYU'),
      ' ',
      ELT(1 + MOD(FLOOR(src.person_key / 7), 20), 'SANTOSO', 'PRATAMA', 'SYAHPUTRA', 'NUGRAHA', 'GUNAWAN', 'SETIAWAN', 'FIRMANSYAH', 'SAPUTRA', 'KURNIAWAN', 'HIDAYAT', 'MAULANA', 'RAHMAN', 'WIJAYA', 'SIREGAR', 'TANJUNG', 'NASUTION', 'LUBIS', 'HUTAGALUNG', 'HADINATA', 'PANGESTU')
    )
  END AS NAMA_LENGKAP,
  IF(MOD(src.n, 37) = 0, '', LPAD(src.person_key, 16, '0')) AS NIK,
  IF(MOD(src.n, 4) = 0, CONCAT('ALIAS ', ELT(1 + MOD(src.n, 10), 'BOY', 'JAY', 'UDI', 'ANDI', 'RAMA', 'BAY', 'MAN', 'DAN', 'GUS', 'TON')), '') AS NAMA_ALIAS1,
  IF(MOD(src.n, 9) = 0, CONCAT('ALIAS ', ELT(1 + MOD(src.n, 10), 'RA', 'AL', 'SU', 'JO', 'RY', 'FA', 'AR', 'YU', 'ZA', 'RE')), '') AS NAMA_ALIAS2,
  IF(MOD(src.n, 17) = 0, CONCAT('ALIAS ', ELT(1 + MOD(src.n, 10), 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X0')), '') AS NAMA_ALIAS3,
  IF(MOD(src.n, 5) = 0, ELT(1 + MOD(src.person_key, 10), 'BUDI', 'AHMAD', 'JOKO', 'RIZKY', 'FAJAR', 'BAGUS', 'RAMA', 'YUSUF', 'DANI', 'AGUS'), '') AS NAMA_KECIL1,
  IF(MOD(src.n, 13) = 0, ELT(1 + MOD(src.person_key, 10), 'ARI', 'RUDI', 'BAYU', 'YOGA', 'ILHAM', 'RIZAL', 'IRFAN', 'SANDI', 'TONI', 'DANI'), '') AS NAMA_KECIL2,
  IF(MOD(src.n, 29) = 0, ELT(1 + MOD(src.person_key, 10), 'BOY', 'JAY', 'UDI', 'ANDI', 'RAMA', 'BAY', 'MAN', 'DAN', 'GUS', 'TON'), '') AS NAMA_KECIL3,
  DATE_ADD('1970-01-01', INTERVAL MOD(src.person_key, 18000) DAY) AS TANGGAL_LAHIR,
  IF(MOD(src.person_key, 30) = 0, 1, 0) AS IS_WBP_BERESIKO_TINGGI,
  IF(MOD(src.person_key, 40) = 0, 1, 0) AS IS_PENGARUH_TERHADAP_MASYARAKAT,
  IF(MOD(src.person_key, 5) = 0, 1, 0) AS IS_BACA_LATIN,
  IF(MOD(src.person_key, 7) = 0, 1, 0) AS IS_BACA_QURAN,
  IF(MOD(src.person_key, 100) = 0, 1, 0) AS IS_DISABILITAS,
  CONCAT('JL TEST NO ', MOD(src.person_key, 5000), ' KEL ', MOD(src.person_key, 200)) AS ALAMAT,
  IF(MOD(src.n, 11) = 0, CONCAT('ALT ', MOD(src.n, 9999), ' BLOK ', MOD(src.person_key, 50)), '') AS ALAMAT_ALTERNATIF,
  LPAD(10000 + MOD(src.person_key, 89999), 5, '0') AS KODEPOS,
  CONCAT('08', LPAD(MOD(src.person_key * 31, 10000000000), 10, '0')) AS TELEPON,
  CONCAT('KAWASAN ', MOD(src.person_key, 300)) AS ALAMAT_PEKERJAAN,
  CONCAT('PEKERJAAN ', MOD(src.person_key, 25)) AS KETERANGAN_PEKERJAAN,
  CONCAT('MINAT ', MOD(src.person_key, 15)) AS MINAT,
  CONCAT('AYAH ', ELT(1 + MOD(src.person_key, 20), 'SANTOSO', 'PRATAMA', 'SYAHPUTRA', 'NUGRAHA', 'GUNAWAN', 'SETIAWAN', 'FIRMANSYAH', 'SAPUTRA', 'KURNIAWAN', 'HIDAYAT', 'MAULANA', 'RAHMAN', 'WIJAYA', 'SIREGAR', 'TANJUNG', 'NASUTION', 'LUBIS', 'HUTAGALUNG', 'HADINATA', 'PANGESTU')) AS NM_AYAH,
  CONCAT('TMP ', MOD(src.person_key, 300), ' / ', DATE_FORMAT(DATE_ADD('1950-01-01', INTERVAL MOD(src.person_key, 25000) DAY), '%Y-%m-%d')) AS TMP_TGL_AYAH,
  CONCAT('IBU ', ELT(1 + MOD(src.person_key, 20), 'SARI', 'WATI', 'DEWI', 'NINGSIH', 'KURNIA', 'MELATI', 'SUSANTI', 'ROHAYATI', 'FITRI', 'YULI', 'MAWAR', 'NURAINI', 'SULASTRI', 'HARTATI', 'NURHAYATI', 'MARIANI', 'KARTINI', 'JULIANA', 'FATIMAH', 'RUSMINI')) AS NM_IBU,
  CONCAT('TMP ', MOD(src.person_key, 300), ' / ', DATE_FORMAT(DATE_ADD('1955-01-01', INTERVAL MOD(src.person_key, 25000) DAY), '%Y-%m-%d')) AS TMP_TGL_IBU,
  CONCAT('SAUDARA ', MOD(src.person_key, 2000)) AS NM_SAUDARA,
  MOD(src.person_key, 8) + 1 AS ANAKKE,
  MOD(src.person_key, 6) AS JML_SAUDARA,
  MOD(src.person_key, 3) AS JML_ISTRI_SUAMI,
  IF(MOD(src.person_key, 3) = 0, '', CONCAT('PASANGAN ', MOD(src.person_key, 5000))) AS NM_ISTRI_SUAMI,
  CONCAT('TMP ', MOD(src.person_key, 300), ' / ', DATE_FORMAT(DATE_ADD('1975-01-01', INTERVAL MOD(src.person_key, 20000) DAY), '%Y-%m-%d')) AS TMP_TGL_ISTRI_SUAMI,
  MOD(src.person_key, 5) AS JML_ANAK,
  CONCAT('ANAK ', MOD(src.person_key, 5000)) AS NM_ANAK,
  CONCAT('08', LPAD(MOD(src.person_key * 47, 10000000000), 10, '0')) AS TELEPHONE_KELUARGA,
  150 + MOD(src.person_key, 40) AS TINGGI,
  45 + MOD(src.person_key, 60) AS BERAT,
  IF(MOD(src.person_key, 100) = 0, 'DISABILITAS RINGAN', '') AS CACAT,
  CONCAT('CIRI ', MOD(src.person_key, 1000)) AS CIRI,
  CONCAT('CIRI2 ', MOD(src.person_key, 1000)) AS CIRI2,
  CONCAT('CIRI3 ', MOD(src.person_key, 1000)) AS CIRI3,
  '' AS FOTO_DEPAN,
  '' AS FOTO_KANAN,
  '' AS FOTO_KIRI,
  '' AS FOTO_CLOSEUP,
  '' AS FOTO_CIRI_1,
  '' AS FOTO_CIRI_2,
  '' AS FOTO_CIRI_3,
  IF(MOD(src.person_key, 15) = 0, 1, 0) AS KONSOLIDASI,
  IF(MOD(src.person_key, 20) = 0, 1, 0) AS KONSOLIDASI_IMAGE,
  IF(MOD(src.person_key, 4) = 0, '1', '0') AS ID_KACAMATA,
  CONCAT('TLG', MOD(src.person_key, 5)) AS ID_TELINGA,
  CONCAT('KLT', MOD(src.person_key, 6)) AS ID_WARNAKULIT,
  CONCAT('BRM', MOD(src.person_key, 4)) AS ID_BENTUKRAMBUT,
  CONCAT('BBR', MOD(src.person_key, 5)) AS ID_BENTUKBIBIR,
  CONCAT('LGN', MOD(src.person_key, 4)) AS ID_LENGAN,
  IF(MOD(src.n, 41) = 0, '', LPAD(src.person_key, 12, '0')) AS NOMOR_INDUK_NASIONAL,
  IF(MOD(src.n, 3) = 0, 1, 0) AS IS_VERIFIKASI,
  IF(MOD(src.n, 211) = 0, 1, 0) AS IS_DELETED,
  TIMESTAMPADD(DAY, MOD(src.n, 760), '2024-01-01 00:00:00') AS CREATED,
  'seed-script' AS CREATED_BY,
  TIMESTAMPADD(HOUR, MOD(src.n * 7, 24), TIMESTAMPADD(DAY, MOD(src.n, 760), '2024-01-01 00:00:00')) AS UPDATED,
  'seed-script' AS UPDATED_BY,
  TIMESTAMPADD(HOUR, MOD(src.n * 7, 24), TIMESTAMPADD(DAY, MOD(src.n, 760), '2024-01-01 00:00:00')) AS UPDATED_AT
FROM (
  SELECT
    seq.n,
    GREATEST(
      1,
      CASE
        WHEN MOD(seq.n, 25) IN (0, 1, 2) THEN seq.n - MOD(seq.n, 25)
        WHEN MOD(seq.n, 17) = 0 THEN seq.n - 1
        ELSE seq.n
      END
    ) AS person_key,
    1 + MOD(seq.n - 1, 120) AS id_upt_num,
    1 + MOD(FLOOR((seq.n - 1) / 120), 9999) AS seq_num,
    2010 + MOD(FLOOR((seq.n - 1) / (120 * 9999)), 15) AS year_num,
    1 + MOD(FLOOR((seq.n - 1) / (120 * 9999 * 15)), 12) AS month_num,
    1 + MOD(FLOOR((seq.n - 1) / (120 * 9999 * 15 * 12)), 28) AS day_num
  FROM (
    SELECT
      a.n
      + b.n * 10
      + c.n * 100
      + d.n * 1000
      + e.n * 10000
      + f.n * 100000
      + 1 AS n
    FROM (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
  ) seq
  WHERE seq.n <= @seed_rows
) src;

INSERT INTO perkara (
  NOMOR_INDUK,
  ID_UPT,
  STATUS_PERKARA,
  UPDATED_AT
)
SELECT
  it.NOMOR_INDUK,
  SUBSTRING(it.NOMOR_INDUK, 1, 3) AS ID_UPT,
  ELT(1 + MOD(CAST(RIGHT(it.NOMOR_INDUK, 4) AS UNSIGNED), 3), 'aktif', 'banding', 'inkracht') AS STATUS_PERKARA,
  it.UPDATED_AT
FROM identitas it
WHERE MOD(CAST(RIGHT(it.NOMOR_INDUK, 4) AS UNSIGNED), 10) <> 0;

INSERT INTO cif_mapping (
  NOMOR_INDUK,
  CIF_NUMBER,
  CREATED_AT
)
SELECT
  it.NOMOR_INDUK,
  CONCAT('CIF', it.NOMOR_INDUK) AS CIF_NUMBER,
  COALESCE(it.CREATED, CURRENT_TIMESTAMP) AS CREATED_AT
FROM identitas it
WHERE MOD(CAST(RIGHT(it.NOMOR_INDUK, 4) AS UNSIGNED), 13) = 0;
SQL

final_identitas_rows="$(mysql_exec -Nse "SELECT COUNT(*) FROM identitas;")"
final_perkara_rows="$(mysql_exec -Nse "SELECT COUNT(*) FROM perkara;")"
final_cif_rows="$(mysql_exec -Nse "SELECT COUNT(*) FROM cif_mapping;")"
eligible_rows="$(mysql_exec -Nse "SELECT COUNT(*) FROM identitas it LEFT JOIN cif_mapping cm ON it.NOMOR_INDUK = cm.NOMOR_INDUK LEFT JOIN perkara p ON p.NOMOR_INDUK = it.NOMOR_INDUK WHERE cm.NOMOR_INDUK IS NULL AND p.ID_PERKARA IS NOT NULL AND it.NAMA_LENGKAP <> '' AND it.NAMA_LENGKAP NOT LIKE 'NAMA WBP%' AND it.NOMOR_INDUK NOT LIKE '11f066%' AND p.ID_UPT IS NOT NULL;")"
dup_rows="$(mysql_exec -Nse "SELECT SUM(c - 1) FROM (SELECT COUNT(*) AS c FROM identitas GROUP BY NIK, TANGGAL_LAHIR HAVING c > 1) x;")"

echo "Seed complete."
echo "identitas_rows=${final_identitas_rows}"
echo "perkara_rows=${final_perkara_rows}"
echo "cif_mapping_rows=${final_cif_rows}"
echo "eligible_for_custom_query=${eligible_rows}"
echo "approx_duplicate_rows_by_nik_dob=${dup_rows:-0}"
